version: '2.4'
services:
  ###
  # services
  ###
  django:
    build: .
    command: bash -c "
      python -c \"import nltk; nltk.download('wordnet')\"
       && python manage.py runserver 0.0.0.0:8000"
    volumes:
        - .:/app
    ports:
        - "8000:8000"
    tty: true
    stdin_open: true
    runtime: nvidia 
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
  scrapyd:
    build: ./bots/
    command: bash -c "cd /app && ls -la && scrapyd"
    volumes:
        - ./bots/:/app
    ports:
        - "6800:6800"
    depends_on:
      - django
    tty: true
    stdin_open: true
