version: '3'
services:
  ###
  # services
  ###
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
        - .:/app
    ports:
        - "8000:8000"
    tty: true
    stdin_open: true

  scrapyd:
    build: .
    command: bash -c "cd /app/bots && scrapyd"
    volumes:
        - .:/app
    ports:
        - "6800:6800"
    depends_on:
      - django
    tty: true
    stdin_open: true