# Generated by Django 3.0.3 on 2020-03-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('comments', models.TextField()),
                ('hotel_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ScrapeResult',
        ),
    ]
